### ISSUE TITLE
Types alias and customs types are not supported

### ISSUE THREAD

**Issue by eperinan** [frees-io/sbt-frees-protogen#19]
I am trying to generate a `.proto` file from the following case class.

```
import org.joda.time.DateTime

object Models {

  type Metrics = List[Metric]

  @message
  case class Metric(
      metric: String,
      microservice: String,
      node: String,
      value: Float,
      date: DateTime)

  @message
  case class MetricsList(metrics: Metrics)
}
```

After run `sbt protoGen`,  I am getting the `.proto`file but the result is wrong

```
// This file has been automatically generated for use by
// sbt-frees-protogen plugin, from freestyle-rpc service definitions

syntax = "proto3";



message Metric {
   string metric = 1;
   string microservice = 2;
   string node = 3;
   float value = 4;
   DateTime date = 5;
}
           
message MetricsList {
   Metrics metrics = 1;
}
```

There are two wrongs here. 

The first problem is in Message MetricsList, we should have a `repeated Metric metrics = 1;`. It is because, we are not handling properly the type alia.

The second problem is in DateTime. To serialize and deserialize the case class I had to create two implicits to write and extract where we are setting the type that we are going to serialize.

**Comment by enricsangra** [comment]
The issue comes from `ScalaMetaParam2ProtoMessageField`, in the implicit `defaultParam2ProtoMessageField` on `convert` definition.

In the last case, a proper handling of the expression `expr` is needed to convert it recursively. I have no idea how to convert it to transform it to a `Term.Param` to do so.

A part from testing with the scenario you propose, I'd test something like the following block as it might arise new issues.
```
type L = List
type Metrics = L[Metric]
```

**Comment by juanpedromoreno** [comment]
Indeed, type aliases are not supported by now. However, I would consider it as a new enhancement rather than a bug.
